# Generated by Django 5.2.4 on 2025-08-30 19:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_bankaccount'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('account_freeze', 'Account Freeze'), ('account_unfreeze', 'Account Unfreeze'), ('account_close', 'Account Close'), ('account_approve', 'Account Approve'), ('balance_adjustment', 'Balance Adjustment'), ('user_deactivate', 'User Deactivate'), ('user_activate', 'User Activate'), ('password_reset', 'Password Reset'), ('permission_change', 'Permission Change')], help_text='Type of administrative action performed', max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='When the action was performed')),
                ('description', models.TextField(help_text='Detailed description of the action performed')),
                ('reason', models.TextField(blank=True, help_text='Reason for performing this action', null=True)),
                ('additional_data', models.JSONField(blank=True, default=dict, help_text='Additional data related to the action')),
                ('admin_user', models.ForeignKey(help_text='Admin user who performed this action', on_delete=django.db.models.deletion.CASCADE, related_name='admin_actions_performed', to=settings.AUTH_USER_MODEL)),
                ('target_account', models.ForeignKey(blank=True, help_text='Bank account that was the target of this action', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admin_actions', to='accounts.bankaccount')),
                ('target_user', models.ForeignKey(blank=True, help_text='User who was the target of this action', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admin_actions_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Admin Action',
                'verbose_name_plural': 'Admin Actions',
                'db_table': 'admin_actions',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['action_type'], name='admin_actio_action__d7b108_idx'), models.Index(fields=['timestamp'], name='admin_actio_timesta_2d4e8c_idx'), models.Index(fields=['admin_user', 'timestamp'], name='admin_actio_admin_u_04c3a5_idx'), models.Index(fields=['target_user', 'timestamp'], name='admin_actio_target__dbb2e5_idx'), models.Index(fields=['target_account', 'timestamp'], name='admin_actio_target__90ebfd_idx')],
            },
        ),
    ]
