# Generated by Django 5.2.4 on 2025-08-30 18:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_bankaccount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('deposit', 'Deposit'), ('withdrawal', 'Withdrawal'), ('transfer', 'Transfer')], help_text='Type of transaction', max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Transaction amount', max_digits=15)),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='Transaction timestamp')),
                ('description', models.TextField(blank=True, help_text='Optional transaction description', null=True)),
                ('reference_number', models.CharField(help_text='Unique transaction reference number', max_length=20, unique=True)),
                ('sender_balance_after', models.DecimalField(blank=True, decimal_places=2, help_text='Sender account balance after transaction', max_digits=15, null=True)),
                ('receiver_balance_after', models.DecimalField(blank=True, decimal_places=2, help_text='Receiver account balance after transaction', max_digits=15, null=True)),
                ('receiver_account', models.ForeignKey(blank=True, help_text='Account receiving money (for deposits and transfers)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_transactions', to='accounts.bankaccount')),
                ('sender_account', models.ForeignKey(blank=True, help_text='Account sending money (for withdrawals and transfers)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_transactions', to='accounts.bankaccount')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'db_table': 'transactions',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['transaction_type'], name='transaction_transac_ddda52_idx'), models.Index(fields=['timestamp'], name='transaction_timesta_07633a_idx'), models.Index(fields=['sender_account', 'timestamp'], name='transaction_sender__6411f9_idx'), models.Index(fields=['receiver_account', 'timestamp'], name='transaction_receive_884d9c_idx')],
            },
        ),
    ]
