# Generated by Django 5.2.4 on 2025-08-30 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='reference_number',
            field=models.CharField(help_text='Unique transaction reference number', max_length=25, unique=True),
        ),
    ]
